name: show inputs
on:
  workflow_call:
    inputs:
      inputs:
        description: inputs
        type: string
        required: true

jobs:
  show-inputs:
    runs-on: ubuntu-latest

    steps:
      - run: ${{ inputs.inputs }}"
